services:
  app:
    build: .
    container_name: immo_rechner_app
    image: shajian/immo-rechner:0.1.1
    depends_on:
      - nginx
    volumes:
      - ./.env:/immo-rechner/.env

  nginx:
    image: nginx
    container_name: nginx
