services:
  app:
    build: .
    container_name: immo_rechner_app
    image: shajian/immo-rechner:0.1.1
    ports:
      - "8008"
    depends_on:
      - nginx

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8050:8050"
